// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleEfficiencyAcd.Data.Context;

#nullable disable

namespace VehicleEfficiencyAcd.Data.Migrations
{
    [DbContext(typeof(VehicleEfficiencyAcdDbContext))]
    [Migration("20241203231010_BulkSeed Data Added")]
    partial class BulkSeedDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleEfficiencyAcd.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleEfficiencyAcd.Data.Entities.VehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 76, DateTimeKind.Local).AddTicks(8839),
                            ImagePath = "/images/vehicles/ferrari.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8129),
                            Name = "Ferrari",
                            Plate = "26 ACD 999"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8956),
                            ImagePath = "/images/vehicles/corolla.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8959),
                            Name = "Toyota Corolla",
                            Plate = "34 ABC 101"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8961),
                            ImagePath = "/images/vehicles/civic.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8961),
                            Name = "Honda Civic",
                            Plate = "06 DEF 202"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8964),
                            ImagePath = "/images/vehicles/focus.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8964),
                            Name = "Ford Focus",
                            Plate = "35 GHI 303"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8965),
                            ImagePath = "/images/vehicles/bmw320i.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8966),
                            Name = "BMW 320i",
                            Plate = "07 JKL 404"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8967),
                            ImagePath = "/images/vehicles/mercedesc200.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8967),
                            Name = "Mercedes C200",
                            Plate = "16 MNO 505"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8968),
                            ImagePath = "/images/vehicles/audia4.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8969),
                            Name = "Audi A4",
                            Plate = "10 PQR 606"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8970),
                            ImagePath = "/images/vehicles/golf.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8970),
                            Name = "Volkswagen Golf",
                            Plate = "20 STU 707"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8971),
                            ImagePath = "/images/vehicles/altima.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8971),
                            Name = "Nissan Altima",
                            Plate = "26 ABC 808"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8972),
                            ImagePath = "/images/vehicles/elantra.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8973),
                            Name = "Hyundai Elantra",
                            Plate = "42 YZA 909"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8974),
                            ImagePath = "/images/vehicles/cruze.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8974),
                            Name = "Chevrolet Cruze",
                            Plate = "27 BCD 111"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8975),
                            ImagePath = "/images/vehicles/clio.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 77, DateTimeKind.Local).AddTicks(8976),
                            Name = "Renault Clio",
                            Plate = "26 DEF 200"
                        });
                });

            modelBuilder.Entity("VehicleEfficiencyAcd.Data.Entities.VehicleUsageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ActiveHours")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MaintenanceHours")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleUsages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveHours = 102.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(247),
                            IsDeleted = false,
                            MaintenanceHours = 12.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(253),
                            VehicleId = 1,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 2,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(716),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(718),
                            VehicleId = 1,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 3,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(720),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(721),
                            VehicleId = 1,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 4,
                            ActiveHours = 160.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(723),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(723),
                            VehicleId = 1,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 5,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(725),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(725),
                            VehicleId = 1,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 6,
                            ActiveHours = 110.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(727),
                            IsDeleted = false,
                            MaintenanceHours = 10.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(727),
                            VehicleId = 2,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 7,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(729),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(729),
                            VehicleId = 2,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 8,
                            ActiveHours = 168.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(731),
                            IsDeleted = false,
                            MaintenanceHours = 1.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(731),
                            VehicleId = 2,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 9,
                            ActiveHours = 155.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(733),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(733),
                            VehicleId = 2,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 10,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(735),
                            IsDeleted = false,
                            MaintenanceHours = 9.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(735),
                            VehicleId = 2,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 11,
                            ActiveHours = 105.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(737),
                            IsDeleted = false,
                            MaintenanceHours = 11.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(737),
                            VehicleId = 3,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 12,
                            ActiveHours = 170.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(738),
                            IsDeleted = false,
                            MaintenanceHours = 2.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(739),
                            VehicleId = 3,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 13,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(740),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(741),
                            VehicleId = 3,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 14,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(762),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(762),
                            VehicleId = 3,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 15,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(764),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(765),
                            VehicleId = 3,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 16,
                            ActiveHours = 115.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(766),
                            IsDeleted = false,
                            MaintenanceHours = 12.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(767),
                            VehicleId = 4,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 17,
                            ActiveHours = 145.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(768),
                            IsDeleted = false,
                            MaintenanceHours = 9.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(769),
                            VehicleId = 4,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 18,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(770),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(770),
                            VehicleId = 4,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 19,
                            ActiveHours = 160.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(772),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(772),
                            VehicleId = 4,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 20,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(774),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(774),
                            VehicleId = 4,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 21,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(776),
                            IsDeleted = false,
                            MaintenanceHours = 10.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(777),
                            VehicleId = 5,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 22,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(779),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(779),
                            VehicleId = 5,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 23,
                            ActiveHours = 155.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(781),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(782),
                            VehicleId = 5,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 24,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(783),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(784),
                            VehicleId = 5,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 25,
                            ActiveHours = 165.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(785),
                            IsDeleted = false,
                            MaintenanceHours = 2.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(786),
                            VehicleId = 5,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 26,
                            ActiveHours = 105.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(787),
                            IsDeleted = false,
                            MaintenanceHours = 13.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(788),
                            VehicleId = 6,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 27,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(789),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(790),
                            VehicleId = 6,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 28,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(791),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(792),
                            VehicleId = 6,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 29,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(803),
                            IsDeleted = false,
                            MaintenanceHours = 9.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(804),
                            VehicleId = 6,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 30,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(805),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(806),
                            VehicleId = 6,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 31,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(807),
                            IsDeleted = false,
                            MaintenanceHours = 11.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(808),
                            VehicleId = 7,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 32,
                            ActiveHours = 165.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(809),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(810),
                            VehicleId = 7,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 33,
                            ActiveHours = 145.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(811),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(811),
                            VehicleId = 7,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 34,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(813),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(813),
                            VehicleId = 7,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 35,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(815),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(815),
                            VehicleId = 7,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 36,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(816),
                            IsDeleted = false,
                            MaintenanceHours = 10.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(817),
                            VehicleId = 8,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 37,
                            ActiveHours = 155.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(818),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(819),
                            VehicleId = 8,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 38,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(821),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(821),
                            VehicleId = 8,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 39,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(823),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(823),
                            VehicleId = 8,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 40,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(824),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(825),
                            VehicleId = 8,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 41,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(826),
                            IsDeleted = false,
                            MaintenanceHours = 11.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(827),
                            VehicleId = 9,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 42,
                            ActiveHours = 165.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(828),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(829),
                            VehicleId = 9,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 43,
                            ActiveHours = 145.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(830),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(842),
                            VehicleId = 9,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 44,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(844),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(844),
                            VehicleId = 9,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 45,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(846),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(846),
                            VehicleId = 9,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 46,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(848),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(848),
                            VehicleId = 10,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 47,
                            ActiveHours = 170.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(850),
                            IsDeleted = false,
                            MaintenanceHours = 1.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(850),
                            VehicleId = 10,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 48,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(852),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(852),
                            VehicleId = 10,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 49,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(854),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(854),
                            VehicleId = 10,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 50,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(855),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(856),
                            VehicleId = 10,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 51,
                            ActiveHours = 105.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(858),
                            IsDeleted = false,
                            MaintenanceHours = 13.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(858),
                            VehicleId = 11,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 52,
                            ActiveHours = 160.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(859),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(860),
                            VehicleId = 11,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 53,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(861),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(862),
                            VehicleId = 11,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 54,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(863),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(864),
                            VehicleId = 11,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 55,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(865),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(866),
                            VehicleId = 11,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 56,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(867),
                            IsDeleted = false,
                            MaintenanceHours = 10.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(867),
                            VehicleId = 12,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 57,
                            ActiveHours = 145.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(869),
                            IsDeleted = false,
                            MaintenanceHours = 9.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(869),
                            VehicleId = 12,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 58,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(871),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(871),
                            VehicleId = 12,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 59,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(872),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(873),
                            VehicleId = 12,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 60,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(874),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 10, 10, 84, DateTimeKind.Local).AddTicks(875),
                            VehicleId = 12,
                            Week = "W5"
                        });
                });

            modelBuilder.Entity("VehicleEfficiencyAcd.Data.Entities.VehicleUsageEntity", b =>
                {
                    b.HasOne("VehicleEfficiencyAcd.Data.Entities.VehicleEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
