// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleEfficiencyAcd.Data.Context;

#nullable disable

namespace VehicleEfficiencyAcd.Data.Migrations
{
    [DbContext(typeof(VehicleEfficiencyAcdDbContext))]
    [Migration("20241203231352_Seed Data Added")]
    partial class SeedDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleEfficiencyAcd.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleEfficiencyAcd.Data.Entities.VehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 994, DateTimeKind.Local).AddTicks(2812),
                            ImagePath = "/images/vehicles/ferrari.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(2228),
                            Name = "Ferrari",
                            Plate = "26 ACD 999"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3125),
                            ImagePath = "/images/vehicles/clio.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3127),
                            Name = "Renault Clio",
                            Plate = "26 DEF 200"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3129),
                            ImagePath = "/images/vehicles/corolla.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3129),
                            Name = "Toyota Corolla",
                            Plate = "34 ABC 101"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3130),
                            ImagePath = "/images/vehicles/civic.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3131),
                            Name = "Honda Civic",
                            Plate = "06 DEF 202"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3132),
                            ImagePath = "/images/vehicles/focus.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3133),
                            Name = "Ford Focus",
                            Plate = "35 GHI 303"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3134),
                            ImagePath = "/images/vehicles/bmw320i.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3134),
                            Name = "BMW 320i",
                            Plate = "07 JKL 404"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3135),
                            ImagePath = "/images/vehicles/mercedesc200.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3136),
                            Name = "Mercedes C200",
                            Plate = "16 MNO 505"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3137),
                            ImagePath = "/images/vehicles/audia4.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3137),
                            Name = "Audi A4",
                            Plate = "10 PQR 606"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3138),
                            ImagePath = "/images/vehicles/golf.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3139),
                            Name = "Volkswagen Golf",
                            Plate = "20 STU 707"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3140),
                            ImagePath = "/images/vehicles/altima.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3140),
                            Name = "Nissan Altima",
                            Plate = "26 ABC 808"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3141),
                            ImagePath = "/images/vehicles/elantra.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3141),
                            Name = "Hyundai Elantra",
                            Plate = "42 YZA 909"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3142),
                            ImagePath = "/images/vehicles/cruze.jpg",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 51, 995, DateTimeKind.Local).AddTicks(3143),
                            Name = "Chevrolet Cruze",
                            Plate = "27 BCD 111"
                        });
                });

            modelBuilder.Entity("VehicleEfficiencyAcd.Data.Entities.VehicleUsageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ActiveHours")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MaintenanceHours")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleUsages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveHours = 102.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(2646),
                            IsDeleted = false,
                            MaintenanceHours = 12.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(2650),
                            VehicleId = 1,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 2,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3094),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3094),
                            VehicleId = 1,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 3,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3096),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3097),
                            VehicleId = 1,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 4,
                            ActiveHours = 160.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3098),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3098),
                            VehicleId = 1,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 5,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3099),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3100),
                            VehicleId = 1,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 6,
                            ActiveHours = 110.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3101),
                            IsDeleted = false,
                            MaintenanceHours = 10.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3101),
                            VehicleId = 2,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 7,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3102),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3103),
                            VehicleId = 2,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 8,
                            ActiveHours = 168.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3104),
                            IsDeleted = false,
                            MaintenanceHours = 1.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3104),
                            VehicleId = 2,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 9,
                            ActiveHours = 155.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3105),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3106),
                            VehicleId = 2,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 10,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3107),
                            IsDeleted = false,
                            MaintenanceHours = 9.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3107),
                            VehicleId = 2,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 11,
                            ActiveHours = 105.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3108),
                            IsDeleted = false,
                            MaintenanceHours = 11.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3109),
                            VehicleId = 3,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 12,
                            ActiveHours = 170.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3110),
                            IsDeleted = false,
                            MaintenanceHours = 2.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3110),
                            VehicleId = 3,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 13,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3112),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3112),
                            VehicleId = 3,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 14,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3128),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3128),
                            VehicleId = 3,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 15,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3129),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3129),
                            VehicleId = 3,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 16,
                            ActiveHours = 115.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3131),
                            IsDeleted = false,
                            MaintenanceHours = 12.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3131),
                            VehicleId = 4,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 17,
                            ActiveHours = 145.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3132),
                            IsDeleted = false,
                            MaintenanceHours = 9.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3132),
                            VehicleId = 4,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 18,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3134),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3134),
                            VehicleId = 4,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 19,
                            ActiveHours = 160.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3135),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3135),
                            VehicleId = 4,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 20,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3137),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3137),
                            VehicleId = 4,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 21,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3138),
                            IsDeleted = false,
                            MaintenanceHours = 10.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3138),
                            VehicleId = 5,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 22,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3140),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3140),
                            VehicleId = 5,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 23,
                            ActiveHours = 155.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3141),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3142),
                            VehicleId = 5,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 24,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3143),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3143),
                            VehicleId = 5,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 25,
                            ActiveHours = 165.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3144),
                            IsDeleted = false,
                            MaintenanceHours = 2.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3145),
                            VehicleId = 5,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 26,
                            ActiveHours = 105.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3146),
                            IsDeleted = false,
                            MaintenanceHours = 13.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3146),
                            VehicleId = 6,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 27,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3147),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3148),
                            VehicleId = 6,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 28,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3149),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3149),
                            VehicleId = 6,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 29,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3158),
                            IsDeleted = false,
                            MaintenanceHours = 9.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3159),
                            VehicleId = 6,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 30,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3160),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3160),
                            VehicleId = 6,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 31,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3161),
                            IsDeleted = false,
                            MaintenanceHours = 11.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3162),
                            VehicleId = 7,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 32,
                            ActiveHours = 165.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3163),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3163),
                            VehicleId = 7,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 33,
                            ActiveHours = 145.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3164),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3165),
                            VehicleId = 7,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 34,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3166),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3167),
                            VehicleId = 7,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 35,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3168),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3168),
                            VehicleId = 7,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 36,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3169),
                            IsDeleted = false,
                            MaintenanceHours = 10.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3169),
                            VehicleId = 8,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 37,
                            ActiveHours = 155.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3171),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3171),
                            VehicleId = 8,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 38,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3172),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3173),
                            VehicleId = 8,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 39,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3174),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3174),
                            VehicleId = 8,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 40,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3175),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3176),
                            VehicleId = 8,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 41,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3177),
                            IsDeleted = false,
                            MaintenanceHours = 11.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3177),
                            VehicleId = 9,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 42,
                            ActiveHours = 165.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3178),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3179),
                            VehicleId = 9,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 43,
                            ActiveHours = 145.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3180),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3187),
                            VehicleId = 9,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 44,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3236),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3236),
                            VehicleId = 9,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 45,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3237),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3238),
                            VehicleId = 9,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 46,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3239),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3239),
                            VehicleId = 10,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 47,
                            ActiveHours = 170.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3240),
                            IsDeleted = false,
                            MaintenanceHours = 1.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3241),
                            VehicleId = 10,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 48,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3242),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3242),
                            VehicleId = 10,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 49,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3243),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3244),
                            VehicleId = 10,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 50,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3245),
                            IsDeleted = false,
                            MaintenanceHours = 8.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3245),
                            VehicleId = 10,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 51,
                            ActiveHours = 105.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3246),
                            IsDeleted = false,
                            MaintenanceHours = 13.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3247),
                            VehicleId = 11,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 52,
                            ActiveHours = 160.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3248),
                            IsDeleted = false,
                            MaintenanceHours = 3.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3248),
                            VehicleId = 11,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 53,
                            ActiveHours = 140.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3250),
                            IsDeleted = false,
                            MaintenanceHours = 4.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3250),
                            VehicleId = 11,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 54,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3251),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3251),
                            VehicleId = 11,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 55,
                            ActiveHours = 125.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3252),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3253),
                            VehicleId = 11,
                            Week = "W5"
                        },
                        new
                        {
                            Id = 56,
                            ActiveHours = 120.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3254),
                            IsDeleted = false,
                            MaintenanceHours = 10.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3254),
                            VehicleId = 12,
                            Week = "W1"
                        },
                        new
                        {
                            Id = 57,
                            ActiveHours = 145.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3255),
                            IsDeleted = false,
                            MaintenanceHours = 9.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3256),
                            VehicleId = 12,
                            Week = "W2"
                        },
                        new
                        {
                            Id = 58,
                            ActiveHours = 130.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3257),
                            IsDeleted = false,
                            MaintenanceHours = 6.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3257),
                            VehicleId = 12,
                            Week = "W3"
                        },
                        new
                        {
                            Id = 59,
                            ActiveHours = 150.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3258),
                            IsDeleted = false,
                            MaintenanceHours = 5.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3259),
                            VehicleId = 12,
                            Week = "W4"
                        },
                        new
                        {
                            Id = 60,
                            ActiveHours = 135.0,
                            CreatedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3260),
                            IsDeleted = false,
                            MaintenanceHours = 7.0,
                            ModifiedDate = new DateTime(2024, 12, 4, 2, 13, 52, 1, DateTimeKind.Local).AddTicks(3260),
                            VehicleId = 12,
                            Week = "W5"
                        });
                });

            modelBuilder.Entity("VehicleEfficiencyAcd.Data.Entities.VehicleUsageEntity", b =>
                {
                    b.HasOne("VehicleEfficiencyAcd.Data.Entities.VehicleEntity", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
